import { useState, useEffect } from 'react'
import Layout from '../components/Layout'
import api from '../utils/api'
import jsPDF from 'jspdf'

export default function ResumeExport() {
  const [resumes, setResumes] = useState([])
  const [selected, setSelected] = useState(null)
  const [resume, setResume] = useState(null)
  const [template, setTemplate] = useState('modern')
  const [generating, setGenerating] = useState(false)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.get('/api/resume/all')
      .then(r => { setResumes(r.data); if (r.data[0]) setSelected(r.data[0].id) })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  useEffect(() => {
    if (selected) {
      api.get(`/api/resume/${selected}`)
        .then(r => setResume(r.data))
        .catch(() => {})
    }
  }, [selected])

  const generatePDF = async () => {
    if (!resume) return
    setGenerating(true)
    try {
      const doc = new jsPDF()
      const text = resume.rawText || ''
      const lines = text.split('\n').filter(l => l.trim())

      if (template === 'modern') {
        // Header
        doc.setFillColor(10, 22, 40)
        doc.rect(0, 0, 210, 40, 'F')
        doc.setTextColor(201, 168, 76)
        doc.setFontSize(22)
        doc.setFont('helvetica', 'bold')
        doc.text(resume.title || 'Resume', 15, 20)
        doc.setTextColor(200, 200, 200)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.text('Generated by ResumeIQ', 15, 32)

        // Content
        doc.setTextColor(30, 30, 30)
        doc.setFontSize(10)
        let y = 55
        lines.forEach(line => {
          if (y > 270) { doc.addPage(); y = 20 }
          const trimmed = line.trim()
          if (trimmed.toUpperCase() === trimmed && trimmed.length > 3 && trimmed.length < 30) {
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(12)
            doc.setTextColor(10, 22, 40)
            y += 4
          } else {
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(10)
            doc.setTextColor(50, 50, 50)
          }
          const wrapped = doc.splitTextToSize(trimmed, 180)
          doc.text(wrapped, 15, y)
          y += wrapped.length * 6 + 2
        })
      } else if (template === 'minimal') {
        doc.setTextColor(30, 30, 30)
        doc.setFontSize(18)
        doc.setFont('helvetica', 'bold')
        doc.text(resume.title || 'Resume', 15, 20)
        doc.setDrawColor(200, 200, 200)
        doc.line(15, 25, 195, 25)

        let y = 40
        lines.forEach(line => {
          if (y > 270) { doc.addPage(); y = 20 }
          const trimmed = line.trim()
          if (trimmed.toUpperCase() === trimmed && trimmed.length > 3) {
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(11)
            doc.setTextColor(0, 0, 0)
            y += 3
          } else {
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(10)
            doc.setTextColor(60, 60, 60)
          }
          const wrapped = doc.splitTextToSize(trimmed, 180)
          doc.text(wrapped, 15, y)
          y += wrapped.length * 6 + 1
        })
      } else if (template === 'classic') {
        doc.setFillColor(240, 240, 240)
        doc.rect(0, 0, 210, 35, 'F')
        doc.setTextColor(10, 22, 40)
        doc.setFontSize(20)
        doc.setFont('helvetica', 'bold')
        doc.text(resume.title || 'Resume', 105, 18, { align: 'center' })
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(100, 100, 100)
        doc.text('Created with ResumeIQ AI Platform', 105, 28, { align: 'center' })

        let y = 50
        lines.forEach(line => {
          if (y > 270) { doc.addPage(); y = 20 }
          const trimmed = line.trim()
          if (trimmed.toUpperCase() === trimmed && trimmed.length > 3) {
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(11)
            doc.setTextColor(10, 22, 40)
            y += 4
          } else {
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(10)
            doc.setTextColor(50, 50, 50)
          }
          const wrapped = doc.splitTextToSize(trimmed, 180)
          doc.text(wrapped, 15, y)
          y += wrapped.length * 6 + 2
        })
      }

      doc.save(`${resume.title || 'resume'}-${template}.pdf`)
    } catch (e) {
      alert('PDF generation failed: ' + e.message)
    } finally {
      setGenerating(false)
    }
  }

  return (
    <Layout>
      <div className="page-header">
        <h2 className="page-title">Export Resume as PDF</h2>
        <p className="page-subtitle">Download your resume in a professional ATS-friendly PDF format</p>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '3rem' }}>
          <div className="spinner" style={{ margin: '0 auto' }} />
        </div>
      ) : resumes.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <p>No resumes found. Upload one first!</p>
        </div>
      ) : (
        <div className="grid-2" style={{ alignItems: 'start' }}>
          <div>
            <div className="card" style={{ marginBottom: '1rem' }}>
              <h4 style={{ color: 'var(--navy-800)', marginBottom: '1rem' }}>Select Resume</h4>
              <div className="form-group">
                <select className="form-select" value={selected || ''} onChange={e => setSelected(parseInt(e.target.value))}>
                  {resumes.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}
                </select>
              </div>
            </div>

            <div className="card" style={{ marginBottom: '1rem' }}>
              <h4 style={{ color: 'var(--navy-800)', marginBottom: '1rem' }}>Choose Template</h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {[
                  { id: 'modern', name: 'Modern Navy', desc: 'Dark header with gold accent — professional and bold' },
                  { id: 'minimal', name: 'Minimal Clean', desc: 'Simple black and white — ATS optimized' },
                  { id: 'classic', name: 'Classic Gray', desc: 'Traditional centered header — timeless design' },
                ].map(t => (
                  <div key={t.id} onClick={() => setTemplate(t.id)}
                    style={{ padding: '12px', border: `2px solid ${template === t.id ? 'var(--gold-500)' : 'var(--gray-200)'}`, borderRadius: 'var(--border-radius)', cursor: 'pointer', background: template === t.id ? 'rgba(201,168,76,0.05)' : 'white' }}>
                    <div style={{ fontWeight: '600', color: 'var(--navy-800)', fontSize: '0.9rem' }}>{t.name}</div>
                    <div style={{ color: 'var(--gray-500)', fontSize: '0.8125rem' }}>{t.desc}</div>
                  </div>
                ))}
              </div>
            </div>

            <button className="btn btn-primary btn-full" onClick={generatePDF} disabled={generating || !resume}>
              {generating ? '⏳ Generating PDF...' : '📄 Download PDF'}
            </button>
          </div>

          <div className="card" style={{ background: 'var(--gray-50)' }}>
            <h4 style={{ color: 'var(--navy-800)', marginBottom: '1rem' }}>Preview</h4>
            {resume ? (
              <div style={{ background: 'white', borderRadius: '8px', padding: '1.5rem', border: '1px solid var(--gray-200)', minHeight: '400px', fontSize: '0.8125rem', color: 'var(--gray-700)', lineHeight: '1.7', whiteSpace: 'pre-wrap', overflowY: 'auto', maxHeight: '500px' }}>
                {resume.rawText?.slice(0, 1500) || 'No content'}
                {resume.rawText?.length > 1500 && <span style={{ color: 'var(--gray-400)' }}>... (truncated for preview)</span>}
              </div>
            ) : (
              <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--gray-400)' }}>
                Select a resume to preview
              </div>
            )}
          </div>
        </div>
      )}
    </Layout>
  )
}